TechStreamConference/website-backend

app/Language/en/Validation.php, app/Validation/PasswordRules.php, app/Validation/PasswordRulesError.php
As soon as the frontend also does a full validation, these error codes will only be helpful as a fallback and should never be necessary to be read in the frontend.
=> return error codes on failed password validation instead of human-readable text messages

app/Controllers/Event.php, app/Database/Migrations/2024-10-07-172154_AddTeamMember.php, app/Database/Seeds/MainSeeder.php, app/Database/Seeds/TeamMemberSeeder.php, app/Models/GenericRoleModel.php, app/Models/SpeakerModel.php, app/Models/TeamMemberModel.php
This will extend the JSON structure that's returned by the events endpoint. It will now look like this:
```json
{
"event": {
// ...
},
"speakers": [
// ...
],
"team_members": [
// ...
]
}
```
The `team_members` field is structured in the exact same way as the `speakers` field.
=> feat: add table for team members and return their data as part of the Event data structure

app/Controllers/Event.php, app/Database/Migrations/2024-11-02-173722_AddEventPublishDate.php, app/Database/Seeds/EventSeeder.php, app/Database/Seeds/GlobalsSeeder.php, app/Models/EventModel.php, app/Models/GlobalsModel.php
- events now have a `publish_date` and are only visible if that date has already passed
- `default_year` has been removed from the globals
- the `api/events` route now defaults to the newest event that has already been published (which is 2024 using the data that's inside the seeders)
=> feat: publish date for events

app/Config/Routes.php, app/Controllers/Account.php, app/Database/Migrations/2025-01-06-153009_AddPasswordResetToken.php, app/Models/AccountModel.php, app/Models/PasswordResetTokenModel.php, app/Views/email/account/forgot_password.php, app/Views/email/account/password_reset.php, composer.json, requests/account/forgot_password.http, requests/account/set_new_password.http
This PR introduces two new endpoints:
- `api/account/forgot-password`: requires the `username_or_email`, sends an email to the user with a randomly generated token to set a new password
- `account/reset-password`: requires the `token` and `new_password`, sets the password for the user to whom the token corresponds, sends a notification email
Tokens are valid for 24 hours. Expired tokens are deleted when any user tries to log in and when a user tries to use a token. This should complete the backend part of the [login use case](https://github.com/TechStreamConference/entity-relationship-model/blob/9f42c1171a97f18e7e13cf05f12e3e790564f3f3/system-tests/login.png).
=> "forgot password" mechanic

app/Controllers/Account.php, app/Database/Migrations/2025-01-06-171157_AddConnectedRegistrationToken.php, app/Database/Seeds/ConnectedRegistrationTokenSeeder.php, app/Database/Seeds/MainSeeder.php, app/Models/ConnectedRegistrationTokenModel.php, requests/account/create_connected_account.http, tests/App/Controllers/AccountTest.php
This PR enhances the `api/account/register` endpoint so that it's now possible to pass an additional `token`. If that token matches a token stored in the new `ConnectedRegistrationToken` table, the newly created account will be connected to the user that's associated with that token (instead of creating a new user). This makes it possible to let users register with their custom username/email/password and still have access to existing speaker (or team member) entries that we have created before.
If a token is provided, but it cannot be found in the database, registration fails.
=> allow registering for an existing user using a predefined token

app/Config/Routes.php, app/Controllers/TimeSlot.php, app/Database/Migrations/2025-01-07-123201_AddTimeSlot.php, app/Helpers/TimeSlotData.php, app/Models/EventModel.php, app/Models/TimeSlotModel.php, requests/time_slots/create_or_replace_time_slots.http, requests/time_slots/get_time_slots.http
This PR adds two new endpoints:
- `GET api/dashboard/admin/time-slots/(:num)`, where `num` is an event id: returns a list of all time slots that correspond to the specified event, e. g.
```json5
[
{
"id": 91,
"event_id": 1,
"start_time": "2024-06-22 13:00:00",
"duration": 45
},
{
"id": 92,
"event_id": 1,
"start_time": "2024-06-22 14:00:00",
"duration": 45
},
// more time slots...
]
```
Possible errors:
- `EVENT_NOT_FOUND` (404)
Otherwise returns status 200.
- `POST api/dashboard/admin/time-slots/(:num)`, where `num` is an event id: Takes JSON data of the following form:
```json5
{
"time_slots": [
{
"start_time": "2024-06-22 13:00:00",
"duration": 45
},
{
"start_time": "2024-06-22 14:00:00",
"duration": 45
},
// more time slots...
]
}
```
The transmitted data is checked (all time slots …
=> Time Slots

app/Config/Routes.php, app/Controllers/Globals.php, app/Models/TalkDurationChoiceModel.php, requests/globals/add_talk_duration_choices.http
New endpoint added:
`POST api/talk-duration-choices`: Requires the admin role, expects data of the following structure:
```json
{
"choices": [15, 30, 60]
}
```
Adds all durations that don't already exist. Returns:
```json5
{ "message": "ADDED_42_CHOICES" } // replace 42 with the actual number of replaced entries
```
=> adding talk duration choices

app/Config/Routes.php, app/Controllers/Globals.php, app/Models/TagModel.php, requests/globals/create_tags.http, requests/globals/update_tags.http
Two new endpoints:
- `PUT api/tags`: Requires the admin role, allows changing existing tags. Expects data of the following structure:
```json
{
"tags": [
{
"id": 1,
"text": "Bastelclub",
"color_index": 1
},
{
"id": 2,
"text": "Forward Engineering",
"color_index": 3
}
]
}
```
Possible errors:
- `TAG_DOES_NOT_EXIST` (400) if there's at least one tag whose ID does not exist
Otherwise, returns `{ "message": "TAGS_UPDATED" }` on success.
- `POST api/tags`: Requires the admin role, allows changing existing tags. Expects data of the following structure:
```json
{
"tags": [
{
"text": "Garbage Collection",
"color_index": 4
},
{
"text": "RAII",
"color_index": 2
}
]
}
```
Possible errors:
- `TAG_ALREADY_EXISTS` (400) if there's at least one whose `text` value matches an existing tag
Otherwise, …
=> ability to update or create tags

app/Config/Routes.php, app/Controllers/Talk.php, app/Models/TalkModel.php, requests/talk/get_all_tentative_or_accepted_talks.http, requests/talk/get_pending_talks_for_speaker.http, requests/talk/get_tentative_or_accepted_talks_for_speaker.http
This PR adds two new endpoints:
- `GET api/dashboard/speaker/pending-talks`: Requires the speaker role, returns an array of all pending (i.e. non-approved) talks or the currently logged in speaker. The returned data has the following structure:
```json5
{
"pending_talks": [
{
"id": 10,
"event_id": 1,
"title": "Programmieren wie ein Profi",
"description": "In diesem Vortrag lernst du, wie du professionell programmierst.",
"notes": "Ich kann nur am zweiten Tag der Konferenz.",
"requested_changes": null,
"created_at": "2025-01-11 13:53:15",
"speaker": {
"id": 2,
"user_id": 1,
"name": "coder2k",
"short_bio": "Test-Conf Host, Software-Entwickler, freier Dozent, Twitch-Partner",
"bio": "Michael (coder2k) hat vor über 20 Jahren 'Turbo Pascal und Delphi für Kids' gelesen und sich seitdem mit dem …
```
=> endpoints to fetch a list of all pending or tentative/accepted talks for the speaker

app/Controllers/Event.php
It was possible to break the frontend when a talk was ready to be shown on the frontpage, but the corresponding speaker was not published at that point. This PR fixes this by hiding the talks of non-published speakers.
=> fix: event data includes talks of speakers that are not yet visible

app/Config/Routes.php, app/Controllers/ContributorDashboard.php
This PR should fix the problem of speakers seeing events that are not publicly visible yet. However, team members will still be able to see those events.
=> fix: only return published events to speakers

app/Controllers/Talk.php
Previously, it was possible to suggest any (non occupied) time slot to a speaker, even if the possible talk durations contradicted the time slot. Now, this is checked and rejected upon mismatch.
=> fix: only allow suggestion time slots with suitable duration

app/Database/Migrations/2024-10-07-172154_AddTeamMember.php, app/Database/Migrations/2024-10-09-154806_AddMediaPartner.php
The object returned from $this->db->getFieldData uses the attribute nullable and not null (like in the config)
The "id" column is not created with the original config because primary key fields are not allowed to be null and are not allowed to have a default value.
The old version created a SQL Statement like this:
`id` int NULL DEFAULT NULL AUTO_INCREMENT,
Not a pretty fix but it works.
=> Fixed MySQL compatibility

app/Controllers/Event.php, app/Controllers/Globals.php, app/Controllers/Talk.php, app/Database/Migrations/2024-10-07-172154_AddTeamMember.php, app/Database/Migrations/2024-10-09-154806_AddMediaPartner.php, app/Models/GenericRoleModel.php, app/Models/GlobalsModel.php, app/Models/UserModel.php, tests/App/Models/SpeakerModelTest.php
Refactor type casting for consistency and clarity.
Replaced legacy casting functions like `intval`, `boolval`, and `strval` with modern type casting syntax `int`, `bool`, and `string` across multiple files. This ensures more consistent and readable code while adhering to modern PHP best practices.
=> Modern code improvements

app/Database/Migrations/2025-01-01-134252_ChangeRolesView.php
MySQL Standard mode includes `ONLY_FULL_GROUP_BY`. With this setting enabled, the roles view throws an error in tests. The removal of the alias "FROM TeamMember t" (which is not used) to "FROM TeamMember" solves the error.
Tests are passing after this change.
=> fix: mysql error on standard settings

app/Config/Routes.php, app/Controllers/Account.php, requests/account/get_account_data.http
This PR adds a new endpoint:
`GET /api/account`, requires the user to be logged in: Returns data of the following structure:
```json
{
"username": "coder2k",
"email": "coder2k@test-conf.de"
}
```
Possible errors: None (except for authorization)
=> feat: endpoint to fetch username and email address of current user

app/Controllers/TimeSlot.php, app/Models/TimeSlotModel.php
This fixes the error that you described in #157. Instead of an exception, you will now get an error response (`CANNOT_DELETE_ASSIGNED_TIME_SLOTS`, 400).
However, please note that you will still have to make changes to your payload. You can find the expected format in the [example request file](https://github.com/TechStreamConference/website-backend/blob/d167f0d6531a4d889c2f33af74a0369ea292b5f3/requests/time_slots/create_or_replace_time_slots.http#L12-L60).
=> fix: catch exception when trying to delete time slots that have already been assigned

app/Config/Routes.php, app/Controllers/Talk.php, requests/admin_dashboard/get_possible_hosts.http
This PR adds a new endpoint `GET api/dashboard/admin/talk/possible-hosts/(:num)` where `(:num)` is the ID of an event. It returns data of the following structure:
```json5
[
{
"id": 8,
"user_id": 5,
"name": "ClausKleber",
"short_bio": "ClausKleber",
"bio": "ClausKleber",
"photo": "1739204704_3ffe80190a57b8987a06.jpg",
"visible_from": "2024-06-01 12:00:00"
},
// possibly more speakers...
]
```
The speakers in the response are suitable as a host for a new panel discussion. That means, the returned IDs can be used in `POST api/dashboard/admin/talk/create`.
Possible errors:
* `EVENT_NOT_FOUND` (404)
=> feat: add endpoint to fetch list of possible hosts of a panel discussion

app/Config/Routes.php, app/Controllers/Talk.php, app/Models/TalkModel.php, requests/talk/get_all_tentative_or_accepted_talks.http
This PR adds a new endpoint `GET api/dashboard/admin/tentative-or-accepted-talks/(:num)` where `(:num)` is the ID of an event. The response has the same structure as `GET api/dashboard/admin/tentative-talks`, but it only contains events for the given event and the events have to be either tentative or accepted.
Possible errors:
* `EVENT_NOT_FOUND` (404)
=> feat: add endpoint to fetch all tentative or accepted talks of a given event

app/Database/Seeds/TagSeeder2024.php, app/Database/Seeds/TalkHasTagSeeder2024.php
This PR groups the color indices of tags by certain categories.
For example: The tag `Spieleentwicklung` has `color_index == 3`. The "sub-tags" `Unity`, `Unreal`, `Game Design`, etc. have `color_index == 4`. That means: Odd values are for the main categories, even values are for sub-categories.
=> feat: group tag colors by categories
